version: '3.8'

services:
  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/onebitflix
    environment:
      NODE_ENV: development
      SERVER_PORT: 3000
      HOST: db
      PORT: 5432
      DATABASE: onebitflix_development
      USERNAME: onebitflix
      PASSWORD: onebitflix
    depends_on:
      - db
  db:
    image: postgres:15.1
    environment:
      POSTGRES_DB: onebitflix_development
      POSTGRES_USER: onebitflix
      POSTGRES_PASSWORD: onebitflix
    ports:
      - "5432:5432"

volumes:
  db: